auctions/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("watchlist", views.watchlist, name="watchlist"),
    path("createlisting", views.createListing, name="createlisting"),
    path('categories', views.categories, name='categories'),
    path('categories/<str:category>', views.CategoryList, name='categoryList'),
    path('listing/<int:listing_id>', views.listingPage, name='listing'),
    path('listing/<int:listing_id>/<str:watchListmode>/', views.listingPage, name='listing'),

    path('addtoWachList/<int:listing_id>', views.addToWatchlist, name='addtoWachList'),
    path('removefromWachList/<int:listing_id>', views.removeFromWatchlist, name='removefromWachList'),
    path('mybids', views.mybids, name='mybids'),
    path('myListings', views.myListings, name='myListings'),
    path('closeListing/<int:listing_id>', views.closedListings, name='closeListing'),


]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    pass

class AuctionListing(models.Model):
    title = models.CharField(max_length=64)
    description = models.TextField()
    starting_bid = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.URLField(blank=True)
    category = models.ForeignKey("Category", on_delete=models.CASCADE, related_name="category", blank=True, null=True)
    closeStatus = models.BooleanField(default=False)
    active = models.BooleanField(default=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name="created_by")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    winner = models.ForeignKey(User, on_delete=models.CASCADE, related_name="winner", blank=True, null=True)

    def __str__(self):
        return f"{self.title}"
class WatchList(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="watchlist")
    listing = models.ForeignKey(AuctionListing, on_delete=models.CASCADE, related_name="watchlist")

    def __str__(self):
        return f"{self.user} - {self.listing}"
class Category(models.Model):
    name = models.CharField(max_length=64)

    def __str__(self):
        return f"{self.name}"    
    
class Bid(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="bid")
    listing = models.ForeignKey(AuctionListing, on_delete=models.CASCADE, related_name="bid")
    bid = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"{self.user} - {self.listing} - {self.bid}"   
    
class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="comment")
    listing = models.ForeignKey(AuctionListing, on_delete=models.CASCADE, related_name="comment")
    comment = models.TextField()

    def __str__(self):
        return f"{self.user} - {self.listing}"    
    

auctions/forms.py
from django import forms
from .models import Bid, Comment

class BidForm(forms.ModelForm):
    def __init__(self, *args, listing=None, **kwargs):
        super().__init__(*args, **kwargs)
        self.listing = listing

    class Meta:
        model = Bid
        fields = ['bid']

    def clean_bid_value(self):
        bid_value = self.cleaned_data['bid_value']
        min_bid_value = self.listing.starting_bid
        if bid_value < min_bid_value:
            raise forms.ValidationError(f'The bid value must be greater than or equal to {min_bid_value}')
        return bid_value


   



class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('comment',)

auctions/views.py
from tkinter.messagebox import Message
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.db.models import Max
from django.db.models import Q




from .models import *
from .forms import BidForm, CommentForm


def login_view(request):
    if request.method == "POST":
        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(
                request,
                "auctions/login.html",
                {"message": "Invalid username and/or password."},
            )
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(
                request, "auctions/register.html", {"message": "Passwords must match."}
            )

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(
                request,
                "auctions/register.html",
                {"message": "Username already taken."},
            )
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "auctions/register.html")


@login_required(login_url="login")
def watchlist(request):
    watchlistofUser = WatchList.objects.filter(user=request.user)
    print(watchlistofUser)
    watchlist_listings = [item.listing for item in watchlistofUser]
    context = {"listings": watchlist_listings}
    return render(request, "auctions/watchlist.html", context)


@login_required(login_url="login")
def CategoryList(request, category):
    categoryName = category
    category = Category.objects.get(name=categoryName)
    watchlistofCategory = AuctionListing.objects.filter(category_id=category.id)
    context = {"listings": watchlistofCategory, "categoryName": categoryName}
    return render(request, "auctions/categoryList.html", context)


@login_required(login_url="login")
def createListing(request):
    if request.method == "POST":
        title = request.POST["title"]
        description = request.POST["description"]
        starting_bid = request.POST["starting_bid"]
        image = request.POST["image"]
        category_name = request.POST["category"]
        category = Category.objects.get(name=category_name)
        user = request.user
        try:
            listing = AuctionListing.objects.create(
                title=title,
                description=description,
                starting_bid=starting_bid,
                image=image,
                category=category,
                created_by=user,
            )
            listing.save()
        except IntegrityError:
            return render(
                request,
                "auctions/createListing.html",
                {"message": "Something went wrong, please try again."},
            )
        return HttpResponseRedirect(reverse("index"))
    else:
        categories = Category.objects.all()
        users = User.objects.all()
        context = {
            "categories": categories,
            "users": users,
        }
        return render(request, "auctions/createListing.html", context)


@login_required(login_url="login")
def categories(request):
    categories = Category.objects.all()
    categories_listings = []

    for category in categories:
        listings = category.category.all()
        categories_listings.append({"category": category, "listings": listings})

    context = {"categories_listings": categories_listings}

    return render(request, "auctions/categories.html", context)


def index(request):
    # listings whose created_by is not the current user
    listings = AuctionListing.objects.exclude(Q(created_by=request.user.id) | Q(active=False))
    watchlist_listings = []
    if request.user.is_authenticated:
        for listing in listings:
            if WatchList.objects.filter(user=request.user, listing=listing).exists():
                watchlist_listings.append(listing)
        print(watchlist_listings)

    context = {"listings": listings, "watchlist_listings": watchlist_listings}
    return render(request, "auctions/index.html", context)


@login_required(login_url="login")
def addToWatchlist(request, listing_id):
    if request.method == "POST":
        listing = AuctionListing.objects.get(id=listing_id)
        user = request.user
        try:
            if WatchList.objects.filter(user=user, listing=listing).exists():
                WatchList.objects.filter(user=user, listing=listing).delete()
            else:
                watchlist = WatchList.objects.create(
                    user=user,
                    listing=listing,
                )
                watchlist.save()
        except IntegrityError:
            return render(
                request,
                "auctions/listingPage.html",
                {"message": "Something went wrong, please try again."},
            )
    return HttpResponseRedirect(reverse("index"))


@login_required(login_url="login")
def removeFromWatchlist(request, listing_id):
    if request.method == "POST":
        listing = AuctionListing.objects.get(id=listing_id)
        user = request.user
        try:
            if WatchList.objects.filter(user=user, listing=listing).exists():
                WatchList.objects.filter(user=user, listing=listing).delete()
        except IntegrityError:
            return render(
                request,
                "auctions/listingPage.html",
                {"message": "Something went wrong, please try again."},
            )
    return HttpResponseRedirect(reverse("watchlist"))


@login_required(login_url="login")
def listingPage(request, listing_id, watchListmode="False"):

    listing = AuctionListing.objects.get(id=listing_id)
    comments = Comment.objects.filter(listing=listing)
    comment_form = CommentForm(request.POST or None)
    num_bids = Bid.objects.filter(listing=listing).count()
    current_bid = listing.starting_bid
    bid_form = BidForm(request.POST or None)
    mybidStatus = Bid.objects.filter(user=request.user, listing=listing).exists()
    if mybidStatus:
        bid = Bid.objects.get(user=request.user, listing=listing)
    else:
        bid = None

    if request.method == "POST":
        if bid_form.is_valid():
           
            bid = bid_form.save(commit=False)
            bid.user = request.user
            bid.listing = listing
            if bid.bid >= current_bid:
                if Bid.objects.filter(user=request.user, listing=listing).exists():
                     Bid.objects.filter(user=request.user, listing=listing).delete()
                bid.save()
                messages.success(request, 'Your bid has been submitted')
                return redirect("listing", listing.id,'True')
            else:
                messages.error(request, f'Bid must be higher than the current bid of {current_bid}')
                return redirect("listing", listing.id,'True')
                
               
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.user = request.user
            comment.listing = listing
            comment.save()
            return redirect("listing", listing.id,'True')


        return HttpResponseRedirect(reverse("listing", args=(listing.id,)))
    if watchListmode == 'True':
        watchListmode = True
    else:
        watchListmode = False
    context = {
        "comment_form": comment_form,
        "comments": comments,
        "listing": listing,
        "num_bids": num_bids,
        "bid_form": bid_form,
        "watchListmode": watchListmode,
        "mybidStatus": mybidStatus,
        "bid": bid,
    }
    return render(request, "auctions/listingPage.html", context)


@login_required(login_url="login")
def mybids(request):
    bids = Bid.objects.filter(user=request.user)
    context = {"bids": bids}

    return render(request, "auctions/bids.html", context)


@login_required(login_url="login")
def myListings(request):
    listings = AuctionListing.objects.filter(created_by=request.user)
    context = {"listings": listings}
    return render(request, "auctions/mylistings.html", context)

def closedListings(request, listing_id):
    listing = AuctionListing.objects.get(id=listing_id)
    listing.active = False
    listing.save()
    listing = AuctionListing.objects.get(id=listing_id)
    # get the highest bid for the listing
    if not Bid.objects.filter(listing=listing).exists():
        listing.winner_id = None
        listing.save()
        return HttpResponseRedirect(reverse("myListings"))
    highest_bid = Bid.objects.filter(listing=listing).aggregate(Max('bid'))['bid__max']
    print(highest_bid)
    # get the user(s) with the highest bid
    winners = Bid.objects.filter(listing=listing, bid=highest_bid).values_list('user', flat=True)
    print(winners[0])

auctions/templates/auctions/bids.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>My Bids</h2>
    <ul class ='bidsView'>
        {% for bid in bids %}
        <li><a  style="font-weight: 600; font-size: 26px;" href="{% url 'listing' bid.listing.id %}">{{ bid.listing.title }}</a></li>
        <h4>Starting Price: ${{bid.listing.starting_bid}}</h4>
        <h4>My bid: ${{bid.bid}}</h4>
        {% if bid.listing.winner %}
        {% if bid.listing.winner.id == user.id %}
            <span style="color: blue; font-size: xx-large;">I won this!</span>
        {% else %}
            <span style="color: red; font-size: xx-large;">I lost this.</span>
        {% endif %}
    {% endif %}
    
      
        {% endfor %}

    </ul>
{% endblock %}

auctions/templates/auctions/categories.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>Categories</h2>
    <ul>
        {% for category in categories_listings %}
        <li><a href="{% url 'categoryList' category.category.name %}">{{ category.category.name }}</a></li>

        {% endfor %}
    </ul>
{% endblock %}

auctions/templates/auctions/categoryList.html
{% extends "auctions/layout.html" %}
{% load static %}


{% block body %}

    {% for listing in listings %}
        <div class="listing" >
            <div class="listing-image">
                <img class = 'imageClass' src="{{ listing.image }}" alt="Image of {{ listing.title }}">
            </div>
            <div class ="rightSide">
                <div class="listing-title">
                    <a href="{% url 'listing' listing.id  %}">{{ listing.title }}</a>

                </div>
                <div class="listing-price">
                    <span style="font-weight: 600; font-size: 16px; font-family: Arial, sans-serif;">Price: $</span>
                {{ listing.starting_bid }}
                </div>
                <div class="listing-description">
                    <span style="font-weight: 600; font-size: 26px;"> {{ listing.description }}</span>
                </div>          
                <div class="listing-category">
                    <span style="font-weight: 600; font-size: 16px; font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif; ">Category: </span>
                    <span style="color: rgb(87, 101, 228);">{{ listing.category }}</span>
                   
                </div>
            </div>
        
        </div>
{% endfor %}
   

    
{% endblock %}  

auctions/templates/auctions/createListing.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Create listing</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

<form action="{% url 'createlisting' %}" method="post">
    {% csrf_token %}
    <div class="form-group">
        <input class="form-control" autofocus type="text" name="title" placeholder="Title">
    </div>
    <div class="form-group">
        <input class="form-control" type="text" name="description" placeholder="Description">
    </div>
    <div class="form-group">
        <input class="form-control" type="text" name="starting_bid" placeholder="Starting Bid">
    </div>
    <div class="form-group">
        <input class="form-control" type="text" name="image" placeholder="Image URL">
    </div>
        <div class="form-group">
            <label for="id_category">Category:</label>
            <select class="form-control" id="id_category" name="category">
            {% for category in categories %}
                <option value="{{ category.name }}">{{ category.name }}</option>
            {% endfor %}
            </select>
        </div>
      <div class="form-group">
        <label for="id_user">Created by:</label>
        <select class="form-control" id="id_user" name="user">
          {% for user in users %}
            <option value="{{ user.id }}">{{ user.username }}</option>
          {% endfor %}
        </select>
      </div>
      
   
    <input class="btn btn-primary" type="submit" value="Create Listing">


    </form>
{% endblock %}

auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}
{% load static %}



{% block body %}
    <h3>Active Listings</h3>
    {% if user.is_authenticated %}
    {% for listing in listings %}
    
    <div class="listing" >
        <div class="listing-image">
            <img class = 'imageClass' src="{{ listing.image }}" alt="Image of {{ listing.title }}">
        </div>
        <div class ="rightSide">
            <div class="listing-title">
                <a href="{% url 'listing' listing.id  %}">{{ listing.title }}</a>
            
              
            </div>
            <div class="listing-price">
                <span style="font-weight: 600; font-size: 16px; font-family: Arial, sans-serif;">Price: $</span>
            {{ listing.starting_bid }}
            </div>
            <div class="listing-description">
                <span style="font-weight: 600; font-size: 22px;"> {{ listing.description }}</span>
            </div>  
            
                <div class="listing-category">
                    <span style="font-weight: 600; font-size: 16px; font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif; ">Category: </span>
                    <span style="color: rgb(92, 95, 122);">{{ listing.category }}</span>
                    <form action="{% url    'addtoWachList' listing.id %}" method="post">
                        {% csrf_token %}
                        <button type="submit" name="watchlist" id="watchlist-btn" class="watchlist-btn">
                          <span id="watchlist-status">{% if listing in watchlist_listings %}
                            <span style="color: red;">Remove from watchlist</span>
                            {% else %}
                            <span style="color: green;">  Add to watchlist</span>
                            {% endif %}</span>
                        </button>
                      </form>
                      
                </div>
               
    </div>

    
       
     


</div>
{% endfor %}
   
{% else %}
    Nothing to Show.
{% endif %}

    
{% endblock %}  

auctions/templates/auctions/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}Auctions{% endblock %}</title>
    {% load static %}
    <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>
    <div class="navbar">
        <div class="navbar-left">
            <h1>Auctions</h1>
        </div>
        <div class="navbar-right">
            <div class="status">
                {% if user.is_authenticated %}
                 Welcome <strong>{{ user.username }}!</strong>
                {% else %}
                    Not signed in.
                {% endif %}
            </div>
            <ul class="nav">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'myListings' %}">My Listings</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'index' %}">Active Listings</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'watchlist' %}">Watchlists</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'createlisting' %}">Create Listing</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'mybids' %}">My Bids</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'categories' %}">Categories</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Log In</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link registerHello" href="{% url 'register' %}">Register</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
    <hr>
    <div class="main">
        {% block body %}
        {% endblock %}
    </div>
</body>
</html>

auctions/templates/auctions/listingPage.html
{% extends "auctions/layout.html" %}

{% block body %}

 
    <div class="container">

        <div class="left">
            <h1>Listing:
                {{ listing.title }}</h1>

            <img src="{{ listing.image }}" alt="{{ listing.title }}" width="500">

                <div class="wrapper">
                    <div class="col-md-8">
                        <h4>Description:</h4>
                        <p>{{ listing.description }}</p>
                        <bold>Starting bid: ${{ listing.starting_bid|floatformat:2 }}</bold>
                        {% if listing.active %}
                        <p>{{ num_bids }}
                            bids so far.</p>
                            <h2>Details</h2>
                            <ul>
                                <p>Listed by:
                                    {{ listing.created_by }}</p>
                                <p>Category:
                                    {{ listing.category }}</p>
                            </ul>
                    </div>

                    <div class="col-md-4">
                        
                        {% if watchListmode %}

                            {% if mybidStatus %}
                                <h1>
                                    Already placed bid at <span style="color:green">${{ bid.bid }}</span></h1>

                                <form  class="formClass" method="post">
                                    {% csrf_token %}
                                    {{ bid_form.as_p }}
                                    <input type="submit" value="Edit Bid"/>
                                    {% if messages %}
                                    {% for message in messages %}
                                      <div class="custom-alert {% if message.tags %}{{ message.tags }}{% endif %}" role="alert">
                                        {{ message }}
                                      </div>
                                    {% endfor %}
                                  {% endif %}
                                  
                                </form>

                            {% else %}
                                <form class="formClass" method="post">
                                    {% csrf_token %}
                                    {{ bid_form.as_p }}
                                    {% if messages %}
                                    {% for message in messages %}
                                      <div class="custom-alert {% if message.tags %}{{ message.tags }}{% endif %}" role="alert">
                                        {{ message }}
                                      </div>
                                    {% endfor %}
                                  {% endif %}
                                  
                                  
                                    <input type="submit" value="Place Bid"/>
                               
                                </form>

                            {% endif %}
                        {% endif %}
                        {% else %}
                        <h1><span style="color:red">Listing Closed!</span></h1>
                        
                        {% endif %}
                        

                        <div>
                            
                        </div>


                    </div>
                </div>
            </div>
            <div class="right">
                <h2>Comments</h2>
                <ul class="comment-list">
                    {% for comment in comments %}
                        <li class="comment">
                            <div class="comment-author">{{ comment.user.username }}</div>
                            <div class="comment-content">{{ comment.comment }}</div>
                        </li>
                        {% empty %}
                        <li>No comments yet.</li>
                    {% endfor %}
                </ul>
                <form method="post">
                    {% csrf_token %}
                    {{ comment_form.as_p }}
                    <input type="submit" value="Add Comment"></form>
                </div>

            </div>

        {% endblock %}

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'register' %}">Register here.</a>

{% endblock %}

auctions/templates/auctions/mylistings.html
{% extends "auctions/layout.html" %}
{% load static %}


{% block body %}
    <h3>My Listings</h3>

    {% for listing in listings %}

        <div class="listing">
            <div class="listing-image">
                <img class='imageClass' src="{{ listing.image }}" alt="Image of {{ listing.title }}"></div>
                <div class="rightSide">
                    <div class="listing-title">
                        <a href="{% url 'listing' listing.id %}">{{ listing.title }}</a>

                    </div>
                    <div class="listing-price">
                        <span style="font-weight: 600; font-size: 16px; font-family: Arial, sans-serif;">Price: $</span>
                        {{ listing.starting_bid }}
                    </div>
                    <div class="listing-description">
                        <span style="font-weight: 600; font-size: 22px;">
                            {{ listing.description }}</span>
                    </div>

                    <div class="listing-category">
                        <span style="font-weight: 600; font-size: 16px; font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif; ">Category:
                        </span>
                        <span style="color: rgb(92, 95, 122);">{{ listing.category }}</span>
                     
                   


                    </div>
                   
                    {% if listing.active %}
                    <form action="{% url    'closeListing' listing.id %}" method="post">
                        {% csrf_token %}
                    <button type="submit" name="watchlist" id="watchlist-btn" class="watchlist-btn">
                        <span id="watchlist-status">
                          <span style="color: red;">Close Listing!</span>
                      
                      </button>
                      </form>   
                        {% else %}
                        <div class="btnandWinner">
                            <button type="submit" name="watchlist" id="watchlist-btn" class="watchlist-btn">
                                <span id="watchlist-status">
                                    <span style="color: green;">Listing Closed!</span>                          
                              </button>
                            <div class="winner">   The winner is <span style="color: green;">{{listing.winner}}</span></div>
                           
                        </div>
            
                         
                          
                      
                    {% endif %}

                </div>


            </div>
        {% endfor %}


    {% endblock %}

auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'login' %}">Log In here.</a>

{% endblock %}